version: '3'

networks:
  microservices-network:
    driver: bridge
  db-network:
    driver: bridge

services:
  nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    networks:
      - microservices-network
    depends_on:
      - authentication-microservice

  authentication-microservice:
    build:
      context: ./backend/authentication-microservice
      dockerfile: Dockerfile
    depends_on:
      - tokens-microservice
      - master-server
      - slave-server
    networks:
      - microservices-network
      - db-network

  tokens-microservice:
    build:
      context: ./backend/tokens-microservice
      dockerfile: Dockerfile
    networks:
      - microservices-network

  postgres:
    build:
      context: ./backend/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  master-server:
    build:
      context: ./backend/master-server
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db-network

  slave-server:
    build:
      context: ./backend/slave-server
      dockerfile: Dockerfile
    depends_on:
     - master-server
    networks:
      - db-network

volumes:
  postgres-data:
